% Use innerjoin to merge tables based on SiteCode
IMPloc = innerjoin(IMP(:, {'SiteCode', 'Date'}), Sites(:, {'CodeCat', 'Latitude', 'Longitude', 'Elevation', 'Pop2020', 'LandArea'}),...
 'LeftKeys', 'SiteCode', 'RightKeys', 'CodeCat');